# Generated by Django 5.0.1 on 2024-01-13 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_alter_genlink_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genlink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 22, 23, 56, 717335), null=True),
        ),
    ]
